### ISSUE TITLE
Null Safety

### ISSUE THREAD

**Issue by vishwajit76** [hamdikahloun/windows_ocr#1]
I tried to implement null safety in your package, but i got error below error. detected ocr text is showed in log.

`[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: FormatException: Unexpected extension byte (at offset 1)
#0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1789:7)
#1      Utf8Decoder.convert (dart:convert/utf.dart:318:42)
#2      StandardMessageCodec.readValueOfType (package:flutter/src/services/message_codecs.dart:463:29)
#3      StandardMessageCodec.readValue (package:flutter/src/services/message_codecs.dart:438:12)
#4      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:601:27)
#5      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
<asynchronous suspension>
#6      WindowsOcr.getOcr (package:windows_ocr/windows_ocr.dart:16:24)`

**Comment by hamdikahloun** [comment]
Hi @vishwajit76 
Can you share your flutter doctor -v please

**Comment by vishwajit76** [comment]
> Hi @vishwajit76 Can you share your flutter doctor -v please

[√] Flutter (Channel dev, 2.6.0-11.0.pre, on Microsoft Windows [Version 10.0.19042.1288], locale en-IN)
    • Flutter version 2.6.0-11.0.pre at D:\flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4b330ddbed (9 weeks ago), 2021-09-16 17:29:58 -0700
    • Engine revision 5b81c6d615
    • Dart version 2.15.0 (build 2.15.0-116.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at F:\Android\SDK
    • Platform android-31, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Professional 2019 16.11.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional
    • Visual Studio Professional 2019 version 16.11.31729.503
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.62.3)
    • VS Code at C:\Users\vishw\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.28.0

[√] Connected device (4 available)
    • Windows (desktop)       • windows • windows-x64     • Microsoft Windows [Version 10.0.19042.1288]
    • Windows (UWP) (desktop) • winuwp  • windows-uwp-x64 • 
    • Chrome (web)            • chrome  • web-javascript  • Google Chrome 94.0.4606.71
    • Edge (web)              • edge    • web-javascript  • Microsoft Edge 95.0.1020.38

! Doctor found issues in 1 category.
Process finished with exit code 0

I dont know what about cpp, ocr is working well but when string value is returned that time error occured.
`result->Success(flutter::EncodableValue(getOcr(file, language).c_str()));`
